version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspaces/${localWorkspaceFolderBasename}:cached
        command: sleep infinity
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:latest
        container_name: mariadb_container
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: your_root_password
            MARIADB_DATABASE: your_database_name
            MARIADB_USER: your_username
            MARIADB_PASSWORD: your_password
        volumes:
            - mariadb_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    mariadb_data:
