version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb-dev
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 20

  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - .:/workspace
    command: sleep infinity  # keep container running for Codespaces
